#!/bin/ash
echo $(date) - Starting Timelapse Record
error=0
FRAME_RATE=$(cat /etc/timelapse-jpegToMp4/input.conf | jq ".[\"outputFrameRate\"]" | cut -d'"' -f2 || echo "")
if [[ "$FRAME_RATE" == "" ]]; then
	echo frameRate must be defined in input.conf file.
	error=1
fi

# Set default timezone if defined otherwise use UTC
TIMEZONE=$(cat /etc/timelapse-jpegToMp4/input.conf | jq ".[\"timezone\"]" | cut -d'"' -f2 || echo "")
if [[ "$TIMEZONE" == "" ]]; then
	echo timezone not defined in input.conf file, using UTC.
	TIMEZONE=UTC
else
	if [ -e /usr/share/zoneinfo/$TIMEZONE ]; then
		echo Using timezone: $TIMEZONE
	else
		echo Invalid timezone defined in input.conf file, using UTC.
		TIMEZONE=UTC
	fi
fi
date
cp /usr/share/zoneinfo/$TIMEZONE /etc/localtime
echo $TIMEZONE >  /etc/timezone
date

if [ $error -eq 1 ]; then
	exit 1
fi

HOUR=24
currentSeconds=$(date +%s)

if [ -e /tmp/fileList.txt ]; then
    rm /tmp/fileList.txt
fi

if [[ "$1" != "" ]]; then                                                                            
        # Process Past Hours                                                                         
        post=$1                                                                                      
else                                                                                                 
        post=-1                                                                                      
fi

while true; do
    if [ $HOUR -ne $(date +%H) ] || [ $post -ge 0 ]; then
        HOUR=$(date +%H)
        lastSeconds=$currentSeconds
        currentSeconds=$(date +%s)
        if [ $(($currentSeconds-$lastSeconds)) -gt 36120 ]; then # Check if transcoding took longer than 1 hour 2 minutes
            echo ERROR: Process is slower than realtime.  Transcoding will skip to current hour.
        fi
        if [ $post -gt 1 ]; then               
                current=/mnt/storage/$(date -d "$post hour ago" "+%Y/%m/%d/%H")
                post=$(($post-1))              
        elif [ $post -eq 1 ]; then             
                break                                                                                                    
        else                                                                                                             
                current=/mnt/storage/$(date -d '1 hour ago' "+%Y/%m/%d/%H")                                              
        fi
        if [ $(find $current -name "*.jpg" -print | wc -l) -ne 0 ]; then
            echo Started Transcode of $current...
            for f in $(find $current -name "*.jpg" -print | sort); do echo "file '$f'" >> /tmp/fileList.txt; done && ffmpeg -hide_banner -safe 0 -f concat -i /tmp/fileList.txt -an -r $FRAME_RATE -y -vcodec libx265 -vf scale="trunc(iw/ohsub)*ohsub:trunc(ih/ovsub)*ovsub:force_original_aspect_ratio=decrease" -pix_fmt yuv420p10le $current/timelapse-$(echo $current | cut -d/ -f4)-$(echo $current | cut -d/ -f5)-$(echo $current | cut -d/ -f6)_$(echo $current | cut -d/ -f7)_$(date +%Z).mp4 && cat /tmp/fileList.txt | cut -d"'" -f2 | xargs rm && rm /tmp/fileList.txt && echo Success. || echo Failed.
            echo Process Time: $(($(date +%s)-$currentSeconds)) seconds.
        else
            echo $current - No Files to transcode.
        fi
    fi
    if [ $post -lt 0 ]; then                                                                                               
        sleep 10;                                                                                                          
    fi
done
exit 0